name: Deploy

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Deployment directory'
        required: true
        required: true
        type: choice
        default: ''
        options:
        - ''
        - dev 
        - prod

jobs:
  Deploy:
    if: github.ref == 'refs/heads/main' && inputs.dir != ''
    uses: DotzInc/github-workflows/.github/workflows/deploy_terragrunt.yml@main
    with:
      runs-on: JOBER-DESKTOP
      target-dir: ${{ inputs.dir }}
    secrets: inherit
  
