name: Terraform GCP Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure Google Cloud Credentials
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > gcp-key.json

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        run: terraform -chdir=terraform plan \
          -var="credentials_file=gcp-key.json" \
          -var="project_id=ambiente_teste" \
          -var="project_name=ambiente_teste" \
          -var="billing_account=XXXXXX-XXXXXX-XXXXXX"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=terraform apply -auto-approve \
          -var="credentials_file=gcp-key.json" \
          -var="project_id=ambiente_teste" \
          -var="project_name=ambiente_teste" \
          -var="billing_account=XXXXXX-XXXXXX-XXXXXX"
